import { Card } from '../Card'
export const cards: Card[] = [
  {
    id: 1,
    header: 'Liam',
    subheader: 'The best dog owner ever',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Millie', 'Ella', 'Baxter'],
  },
  {
    id: 2,
    header: 'Linda',
    subheader: 'The most attentive caring dog owner ever',
    avatar: 'avatar.png',
    title: 'Business Analyst',
    name: 'Linda Li',
    link: 'https://liamneville.me',
    tags: ['Millie', 'Ella', 'Baxter'],
  },
  {
    id: 3,
    header: 'Ted',
    subheader: 'Likes to talk to dogs a lot in their imaginary voices.',
    avatar: 'avatar.png',
    title: 'Biologist',
    name: 'Ted Grosholz',
    link: 'https://liamneville.me',
    tags: ['Brennan', 'Whittie', 'Baxter', 'Ella'],
  },
  {
    id: 4,
    header: 'Donna',
    subheader: 'Loves to imagine her dogs know every word in the dictionary',
    avatar: 'avatar.png',
    title: 'Lawyer',
    name: 'Donna Neville',
    link: 'https://liamneville.me',
    tags: ['Brennan', 'Whittie', 'Baxter', 'Ella'],
  },
  {
    id: 5,
    header: 'Liam',
    subheader: 'The best dog owner ever',
    avatar: 'avatar.png',
    title: 'Developer',
    name: 'Liam Neville',
    link: 'https://liamneville.me',
    tags: ['Millie', 'Ella', 'Baxter'],
  },
  {
    id: 6,
    header: 'Linda',
    subheader: 'The most attentive caring dog owner ever',
    avatar: 'avatar.png',
    title: 'Business Analyst',
    name: 'Linda Li',
    link: 'https://liamneville.me',
    tags: ['Millie', 'Ella', 'Baxter'],
  },
  {
    id: 7,
    header: 'Ted',
    subheader: 'Likes to talk to dogs a lot in their imaginary voices.',
    avatar: 'avatar.png',
    title: 'Biologist',
    name: 'Ted Grosholz',
    link: 'https://liamneville.me',
    tags: ['Brennan', 'Whittie', 'Baxter', 'Ella'],
  },
  {
    id: 8,
    header: 'Donna',
    subheader: 'Loves to imagine her dogs know every word in the dictionary',
    avatar: 'avatar.png',
    title: 'Lawyer',
    name: 'Donna Neville',
    link: 'https://liamneville.me',
    tags: ['Brennan', 'Whittie', 'Baxter', 'Ella'],
  },
]
